// SPDX-License-Identifier: GPL-2.0-or-later
//
// HCI event codes from monitor/bt.h

// ---- Standard HCI Events ----
pub const BT_HCI_EVT_INQUIRY_COMPLETE: u8 = 0x01;
pub const BT_HCI_EVT_INQUIRY_RESULT: u8 = 0x02;
pub const BT_HCI_EVT_CONN_COMPLETE: u8 = 0x03;
pub const BT_HCI_EVT_CONN_REQUEST: u8 = 0x04;
pub const BT_HCI_EVT_DISCONNECT_COMPLETE: u8 = 0x05;
pub const BT_HCI_EVT_AUTH_COMPLETE: u8 = 0x06;
pub const BT_HCI_EVT_REMOTE_NAME_REQUEST_COMPLETE: u8 = 0x07;
pub const BT_HCI_EVT_ENCRYPT_CHANGE: u8 = 0x08;
pub const BT_HCI_EVT_CHANGE_CONN_LINK_KEY_COMPLETE: u8 = 0x09;
pub const BT_HCI_EVT_LINK_KEY_TYPE_CHANGED: u8 = 0x0A;
pub const BT_HCI_EVT_REMOTE_FEATURES_COMPLETE: u8 = 0x0B;
pub const BT_HCI_EVT_REMOTE_VERSION_COMPLETE: u8 = 0x0C;
pub const BT_HCI_EVT_QOS_SETUP_COMPLETE: u8 = 0x0D;
pub const BT_HCI_EVT_CMD_COMPLETE: u8 = 0x0E;
pub const BT_HCI_EVT_CMD_STATUS: u8 = 0x0F;
pub const BT_HCI_EVT_HARDWARE_ERROR: u8 = 0x10;
pub const BT_HCI_EVT_FLUSH_OCCURRED: u8 = 0x11;
pub const BT_HCI_EVT_ROLE_CHANGE: u8 = 0x12;
pub const BT_HCI_EVT_NUM_COMPLETED_PACKETS: u8 = 0x13;
pub const BT_HCI_EVT_MODE_CHANGE: u8 = 0x14;
pub const BT_HCI_EVT_RETURN_LINK_KEYS: u8 = 0x15;
pub const BT_HCI_EVT_PIN_CODE_REQUEST: u8 = 0x16;
pub const BT_HCI_EVT_LINK_KEY_REQUEST: u8 = 0x17;
pub const BT_HCI_EVT_LINK_KEY_NOTIFY: u8 = 0x18;
pub const BT_HCI_EVT_LOOPBACK_COMMAND: u8 = 0x19;
pub const BT_HCI_EVT_DATA_BUFFER_OVERFLOW: u8 = 0x1A;
pub const BT_HCI_EVT_MAX_SLOTS_CHANGE: u8 = 0x1B;
pub const BT_HCI_EVT_CLOCK_OFFSET_COMPLETE: u8 = 0x1C;
pub const BT_HCI_EVT_CONN_PKT_TYPE_CHANGED: u8 = 0x1D;
pub const BT_HCI_EVT_QOS_VIOLATION: u8 = 0x1E;
pub const BT_HCI_EVT_PSCAN_MODE_CHANGE: u8 = 0x1F;
pub const BT_HCI_EVT_PSCAN_REP_MODE_CHANGE: u8 = 0x20;
pub const BT_HCI_EVT_FLOW_SPEC_COMPLETE: u8 = 0x21;
pub const BT_HCI_EVT_INQUIRY_RESULT_WITH_RSSI: u8 = 0x22;
pub const BT_HCI_EVT_REMOTE_EXT_FEATURES_COMPLETE: u8 = 0x23;
pub const BT_HCI_EVT_SYNC_CONN_COMPLETE: u8 = 0x2C;
pub const BT_HCI_EVT_SYNC_CONN_CHANGED: u8 = 0x2D;
pub const BT_HCI_EVT_SNIFF_SUBRATING: u8 = 0x2E;
pub const BT_HCI_EVT_EXT_INQUIRY_RESULT: u8 = 0x2F;
pub const BT_HCI_EVT_ENCRYPT_KEY_REFRESH_COMPLETE: u8 = 0x30;
pub const BT_HCI_EVT_IO_CAPABILITY_REQUEST: u8 = 0x31;
pub const BT_HCI_EVT_IO_CAPABILITY_RESPONSE: u8 = 0x32;
pub const BT_HCI_EVT_USER_CONFIRM_REQUEST: u8 = 0x33;
pub const BT_HCI_EVT_USER_PASSKEY_REQUEST: u8 = 0x34;
pub const BT_HCI_EVT_REMOTE_OOB_DATA_REQUEST: u8 = 0x35;
pub const BT_HCI_EVT_SIMPLE_PAIRING_COMPLETE: u8 = 0x36;
pub const BT_HCI_EVT_LINK_SUPV_TIMEOUT_CHANGED: u8 = 0x38;
pub const BT_HCI_EVT_ENHANCED_FLUSH_COMPLETE: u8 = 0x39;
pub const BT_HCI_EVT_USER_PASSKEY_NOTIFY: u8 = 0x3B;
pub const BT_HCI_EVT_KEYPRESS_NOTIFY: u8 = 0x3C;
pub const BT_HCI_EVT_REMOTE_HOST_FEATURES_NOTIFY: u8 = 0x3D;
pub const BT_HCI_EVT_LE_META_EVENT: u8 = 0x3E;
pub const BT_HCI_EVT_PHY_LINK_COMPLETE: u8 = 0x40;
pub const BT_HCI_EVT_CHANNEL_SELECTED: u8 = 0x41;
pub const BT_HCI_EVT_DISCONN_PHY_LINK_COMPLETE: u8 = 0x42;
pub const BT_HCI_EVT_PHY_LINK_LOSS_EARLY_WARNING: u8 = 0x43;
pub const BT_HCI_EVT_PHY_LINK_RECOVERY: u8 = 0x44;
pub const BT_HCI_EVT_LOGIC_LINK_COMPLETE: u8 = 0x45;
pub const BT_HCI_EVT_DISCONN_LOGIC_LINK_COMPLETE: u8 = 0x46;
pub const BT_HCI_EVT_FLOW_SPEC_MODIFY_COMPLETE: u8 = 0x47;
pub const BT_HCI_EVT_NUM_COMPLETED_DATA_BLOCKS: u8 = 0x48;
pub const BT_HCI_EVT_SHORT_RANGE_MODE_CHANGE: u8 = 0x4C;
pub const BT_HCI_EVT_AMP_STATUS_CHANGE: u8 = 0x4D;
pub const BT_HCI_EVT_TRIGGERED_CLOCK_CAPTURE: u8 = 0x4E;
pub const BT_HCI_EVT_SYNC_TRAIN_COMPLETE: u8 = 0x4F;
pub const BT_HCI_EVT_SYNC_TRAIN_RECEIVED: u8 = 0x50;
pub const BT_HCI_EVT_PERIPHERAL_BROADCAST_RECEIVE: u8 = 0x51;
pub const BT_HCI_EVT_PERIPHERAL_BROADCAST_TIMEOUT: u8 = 0x52;
pub const BT_HCI_EVT_TRUNCATED_PAGE_COMPLETE: u8 = 0x53;
pub const BT_HCI_EVT_PERIPHERAL_PAGE_RESPONSE_TIMEOUT: u8 = 0x54;
pub const BT_HCI_EVT_PERIPHERAL_BROADCAST_CHANNEL_MAP_CHANGE: u8 = 0x55;
pub const BT_HCI_EVT_INQUIRY_RESPONSE_NOTIFY: u8 = 0x56;
pub const BT_HCI_EVT_AUTH_PAYLOAD_TIMEOUT_EXPIRED: u8 = 0x57;

// ---- LE Meta Event Sub-events ----
pub const BT_HCI_EVT_LE_CONN_COMPLETE: u8 = 0x01;
pub const BT_HCI_EVT_LE_ADV_REPORT: u8 = 0x02;
pub const BT_HCI_EVT_LE_CONN_UPDATE_COMPLETE: u8 = 0x03;
pub const BT_HCI_EVT_LE_REMOTE_FEATURES_COMPLETE: u8 = 0x04;
pub const BT_HCI_EVT_LE_LONG_TERM_KEY_REQUEST: u8 = 0x05;
pub const BT_HCI_EVT_LE_CONN_PARAM_REQUEST: u8 = 0x06;
pub const BT_HCI_EVT_LE_DATA_LENGTH_CHANGE: u8 = 0x07;
pub const BT_HCI_EVT_LE_READ_LOCAL_PK256_COMPLETE: u8 = 0x08;
pub const BT_HCI_EVT_LE_GENERATE_DHKEY_COMPLETE: u8 = 0x09;
pub const BT_HCI_EVT_LE_ENHANCED_CONN_COMPLETE: u8 = 0x0A;
pub const BT_HCI_EVT_LE_DIRECT_ADV_REPORT: u8 = 0x0B;
pub const BT_HCI_EVT_LE_PHY_UPDATE_COMPLETE: u8 = 0x0C;
pub const BT_HCI_EVT_LE_EXT_ADV_REPORT: u8 = 0x0D;
pub const BT_HCI_EVT_LE_PA_SYNC_ESTABLISHED: u8 = 0x0E;
pub const BT_HCI_EVT_LE_PA_REPORT: u8 = 0x0F;
pub const BT_HCI_EVT_LE_PA_SYNC_LOST: u8 = 0x10;
pub const BT_HCI_EVT_LE_ADV_SET_TERM: u8 = 0x12;
pub const BT_HCI_EVT_LE_SCAN_REQ_RECEIVED: u8 = 0x13;
pub const BT_HCI_EVT_LE_CHAN_SELECT_ALG: u8 = 0x14;
pub const BT_HCI_EVT_LE_CTE_REQUEST_FAILED: u8 = 0x17;
pub const BT_HCI_EVT_LE_PAST_RECEIVED: u8 = 0x18;
pub const BT_HCI_EVT_LE_CIS_ESTABLISHED: u8 = 0x19;
pub const BT_HCI_EVT_LE_CIS_REQ: u8 = 0x1A;
pub const BT_HCI_EVT_LE_BIG_COMPLETE: u8 = 0x1B;
pub const BT_HCI_EVT_LE_BIG_TERMINATE: u8 = 0x1C;
pub const BT_HCI_EVT_LE_BIG_SYNC_ESTABILISHED: u8 = 0x1D;
pub const BT_HCI_EVT_LE_BIG_SYNC_LOST: u8 = 0x1E;
pub const BT_HCI_EVT_LE_REQ_PEER_SCA_COMPLETE: u8 = 0x1F;
pub const BT_HCI_EVT_LE_BIG_INFO_ADV_REPORT: u8 = 0x22;
pub const BT_HCI_EVT_LE_READ_ALL_REMOTE_FEATURES_COMPLETE: u8 = 0x2B;
pub const BT_HCI_EVT_LE_CS_RD_REM_SUPP_CAP_COMPLETE: u8 = 0x2C;
pub const BT_HCI_EVT_LE_CS_RD_REM_FAE_COMPLETE: u8 = 0x2D;
pub const BT_HCI_EVT_LE_CS_SEC_ENABLE_COMPLETE: u8 = 0x2E;
pub const BT_HCI_EVT_LE_CS_CONFIG_COMPLETE: u8 = 0x2F;
pub const BT_HCI_EVT_LE_CS_PROC_ENABLE_COMPLETE: u8 = 0x30;
pub const BT_HCI_EVT_LE_CS_SUBEVENT_RESULT: u8 = 0x31;
pub const BT_HCI_EVT_LE_CS_SUBEVENT_RESULT_CONTINUE: u8 = 0x32;
pub const BT_HCI_EVT_LE_CS_TEST_END_COMPLETE: u8 = 0x33;
pub const BT_HCI_EVT_LE_FSU_COMPLETE: u8 = 0x35;

/// HCI error codes from monitor/bt.h BT_HCI_ERR_*
pub const BT_HCI_ERR_SUCCESS: u8 = 0x00;
pub const BT_HCI_ERR_UNKNOWN_COMMAND: u8 = 0x01;
pub const BT_HCI_ERR_UNKNOWN_CONN_ID: u8 = 0x02;
pub const BT_HCI_ERR_HARDWARE_FAILURE: u8 = 0x03;
pub const BT_HCI_ERR_PAGE_TIMEOUT: u8 = 0x04;
pub const BT_HCI_ERR_AUTH_FAILURE: u8 = 0x05;
pub const BT_HCI_ERR_PIN_OR_KEY_MISSING: u8 = 0x06;
pub const BT_HCI_ERR_MEM_CAPACITY_EXCEEDED: u8 = 0x07;
pub const BT_HCI_ERR_CONN_ALREADY_EXISTS: u8 = 0x0B;
pub const BT_HCI_ERR_COMMAND_DISALLOWED: u8 = 0x0C;
pub const BT_HCI_ERR_UNSUPPORTED_FEATURE: u8 = 0x11;
pub const BT_HCI_ERR_INVALID_PARAMETERS: u8 = 0x12;
pub const BT_HCI_ERR_LOCAL_HOST_TERM: u8 = 0x16;
pub const BT_HCI_ERR_UNSPECIFIED_ERROR: u8 = 0x1F;
pub const BT_HCI_ERR_ENC_MODE_NOT_ACCEPTABLE: u8 = 0x25;
pub const BT_HCI_ERR_ADV_TIMEOUT: u8 = 0x3C;
pub const BT_HCI_ERR_CONN_FAILED_TO_ESTABLISH: u8 = 0x3E;
pub const BT_HCI_ERR_UNKNOWN_ADVERTISING_ID: u8 = 0x42;
pub const BT_HCI_ERR_CANCELLED: u8 = 0x44;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_event_codes() {
        assert_eq!(BT_HCI_EVT_CMD_COMPLETE, 0x0E);
        assert_eq!(BT_HCI_EVT_CMD_STATUS, 0x0F);
        assert_eq!(BT_HCI_EVT_LE_META_EVENT, 0x3E);
        assert_eq!(BT_HCI_EVT_DISCONNECT_COMPLETE, 0x05);
    }

    #[test]
    fn test_le_subevent_codes() {
        assert_eq!(BT_HCI_EVT_LE_CONN_COMPLETE, 0x01);
        assert_eq!(BT_HCI_EVT_LE_ADV_REPORT, 0x02);
        assert_eq!(BT_HCI_EVT_LE_CIS_ESTABLISHED, 0x19);
    }
}
